= Saif - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MakerManager

---

== Overview
This project protfolio is written to document the author's contribution to MakerManager.
MakerManager is a desktop application for resource management, specialized for 3D printers and makerspaces.
The app is based on AddressBook-Level 4, an application used for teaching Software Engineering principles in NUS. The user interacts with MakerManager using a Command Line Interface (CLI), but can also choose to use the Graphical User Interface (GUI) built in JavaFX. The software is mainly written in Java, and has about 20 thousand lines of code. The project was developed by a team of 4, and you can find out more about the developers in the About Us section.

In short, MakerManager can be used to:

* effectively time-share 3D printers
* see status and time-left for printers
* add prints to a particular printer (or let the software automaitcally optimize it for you)
* login to the system to gain administrative rights, if you are signed up by an existing administrator
* add, remove and maintain printer queues and machines - if you have administrative rights

== Summary of contributions

* *Major enhancement*: added authentication system for administrators
** What it does: allows lab managers to login to the system and gain extra-privileges, which can be used to manage the makerspace effectively.
** Justification: This feature is a must-have because we need to ensure only authorized personnel can edit critical information
** Highlights: This enhancement requires existing and future commands to keep the level of authorization in mind. It required an in-depth analysis of third party libraries. The implementation was challenging as we had to make sure the application had no security loopholes
** Credits: jBcrypt

* *Major enhancement*: added commands for managing prints
** What it does: allows users to manage prints in general, including starting, restarting, cancelling and deleting prints.
** Justification: This feature is the core of the software, as the whole point of the software is to have a dynamic queue that users can leverage on to plan their own prints.
* *Minor enhancement*: Memory-to-File transfer of data modifications for separate files
* *Minor enhancement*: Bug reports and fixes

* *Code contributed*: https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=psyf[Code Dashboard by Reposense]

* *Other contributions*:

** Project management:
*** Managed releases v1.2.1 - v1.4 (4 releases) on GitHub
** Enhancements to features:
*** Wrote some tests for features added in makerManager (Pull Request https://github.com/CS2113-AY1819S1-T09-1/main/pull/43[#43])
** Documentation:
*** Regularly updated User Guide and Developer Guide to keep up with the releases.
*** Standardized the User Guide and Developer Guide formats (Pull Request https://github.com/CS2113-AY1819S1-T09-1/main/pull/153[#153])
** Community:
*** Reviewed most PRs (with non-trivial review comments). (https://github.com/CS2113-AY1819S1-T09-1/main/pulls?q=is%3Apr+reviewed-by%3APsyf+is%3Aclosed[examples])
*** Managed https://github.com/CS2113-AY1819S1-T09-1/main/issues[issue-board] and https://github.com/CS2113-AY1819S1-T09-1/main/milestones[milestones]
*** Contributed to forum discussions (Example: https://github.com/nusCS2113-AY1819S1/forum/issues/87[#87])
*** Reported bugs and suggestions for other teams in the class (https://github.com/CS2113-AY1819S1-F10-3/main/issues?q=is%3Aopen+mentions%3APsyf[examples])
***
** Tools:
*** Integrated a third party library (jBcrypt) to the project (https://github.com/CS2113-AY1819S1-T09-1/main/pull/12[#12])

== Contributions to the User Guide

//TODO better separator for sections
//TODO disclaimer that some of manageJob is done by trufflePirate for both sections

|===
|_Given below are some sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=intro]

include::../UserGuide.adoc[tag=adminMode]

include::../UserGuide.adoc[tag=managejob]

include::../UserGuide.adoc[tag=faq]

include::../UserGuide.adoc[tag=upcoming]

== Contributions to the Developer Guide

|===
|_Given below are a few sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=administratormode]

include::../DeveloperGuide.adoc[tag=dataencryption]

include::../DeveloperGuide.adoc[tag=managejob]

