== Teo Jun Jie - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:source-highlighter: rouge

=== PROJECT: Maker Manager

---

=== Overview
This is a desktop application for managing maker spaces.

It has a GUI but most of the user interactions happen through a CLI (Command Line Interface).

It is a Java application intended for managing 3-D prints, but has capabilities to handle other forms of manufacturing machines as well.

It is written in OOP fashion. It provides a reasonably well-written code that is based on Address Book (level 4).

*Features*:

. A GUI for displaying all available machines at a glance.+

. Two different access levels, for two separate target profiles (see below)

. Ability to manipulate prints, queues, and machines, depending on access level

. More test cases, including automated GUI testing.

. Support for Build Automation using Gradle and for Continuous Integration using Travis CI.

*Target user profile*:

There will be two categories of users for the app. The main user will be students using the makerspace. The second user will be the lab manager

. has a need to manage a significant number shared devices (lab manager)
. has a need to prioritize and queue certain print jobs over others (lab manager)
. has a need to look up when certain devices will be free for use (students)
. prefers typing over mouse input
. is reasonably comfortable using CLI apps

*Value proposition*:

See which 3D printers are being used, and the estimated time left until the equipment will be free. This will reduce system loss and increase the efficiency of all parties involved.

=== Summary of contributions

---

* *Major enhancements*:
   . Added the feature to *add a machine* to makerManager systems
** What it does: Allows an *admin* to add maker manager 3d printer to the system to allow maker manager uses to start using this printer to execute their print jobs.
** Justification: This feature is significant because without this feature, no print jobs can be executed since no printers will be available for users to execute their print jobs.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

   . Added the feature to *add a job to a machine* to makerManager systems
** What it does: Allows a *user* to add a print job to a maker manager 3d printer.
** Justification: This feature is significant because without this feature, a user will not be able to add a print job to the system without this command
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: Fu Tian Yuan wrote the code for version 1.0 of addJob, I integrated addJob into the makerManager system along with the storage and ui.

    . Added the feature to *manage a machine* to makerManager systems
** What it does: Allows a *user* to manage a machine
*** Flush - Remove all jobs from a machine with AUTO feature (flush jobs to all available machines)
*** Clean - Remove all jobs that are of status CANCELLED, FINISHED, DELETING
*** Remove - Remove the machine from makerManager systems (only if the machine does not have any more jobs)
** Justification: This feature is significant because without this feature, machines cannot be effectively managed. When makerManager becomes
more intensively used in the future, there will be a lot of jobs in each machine in which some of this jobs may have already been completed , finished or deleting.
This makes the UI clunky and unusable as users will not be able to find their jobs that they added to the system as it would be too messy. This feature
enhances the user experience and improves the efficieny of the system.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

___

* *Minor enhancement*:
*** Improved editMachine command and resolved the bugs that we had in V1.3
*** File-to-Memory transfer of data modifications for separate files

___

* *Code contributed*: [https://github.com/CS2113-AY1819S1-T09-1/main[Functional code]]

___
* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.4` (2 releases) on GitHub
** Enhancements to existing features:
*** Enhanced manageJobs command by integrating code with UI

** Documentation:
*** Maintained User Guide and Developer Guide for features I worked on.
*** Started User guide and Developer guide development (Pull request https://github.com/CS2113-AY1819S1-T09-1/main/pull/153[#153])
*** Regularly updated User Guide and Developer Guide to keep up with the releases.
*** Improved the User Guide and Developer Guide formats (Pull Request https://github.com/CS2113-AY1819S1-T09-1/main/pull/153[#153])

** Community:
*** Reviewed second most PRs (with non-trivial review comments). (https://github.com/CS2113-AY1819S1-T09-1/main/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Ateojunjie+is%3Aclosed+[examples])
*** Contributed to forum discussions (Example: https://github.com/nusCS2113-AY1819S1/forum/issues/94[#94])
** Tools:
*** Configured travis version 1.0 at the start of the project


=== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===


include::../UserGuide.adoc[tag=addMachine]

:leveloffset: +1

#_AddJob Version 1.2 and 1.3 (Integrated code with storage and UI)_#

include::../UserGuide.adoc[tag=addJob]

include::../UserGuide.adoc[tag=requestDeletion]

include::../UserGuide.adoc[tag=manageMachine]

#_SwapJobs Version 1.2_#

include::../UserGuide.adoc[tag=swapJobs]

#_ManageJob Version 1.3 (Integrated code with storage and UI)_#

include::../UserGuide.adoc[tag=manageJob]

:leveloffset: -1

=== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=modelComponent]

include::../DeveloperGuide.adoc[tag=storageComponent]

include::../DeveloperGuide.adoc[tag=fileStorageSystem]

