= Sean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MakerManager

---

== Overview
MakerManager is an open-sourced, free desktop application created specifically for Users and Managers of MakerSpaces
to manage 3-D printers and 3-D prints. It aims to help alleviate the hassle and stress related to sharing limited number of
3-D printers by providing an convenient way of organizing Prints, and optimising the usage of Printers.
The app is driven mostly by Command Line Interface (CLI), and therefore optimised for makers who are more
comfortable with typing.

MakerManager is based on AddressBook-Level 4, an application written by educators from the National Universtiy of Singapore
to teach students the fundamentals of Software Engineering and Object Oriented Programming.


In summary, the MakerManager provides:

* an overview of 3-D printers and PrintJobs within a MakerSpace
* functionality to manage and monitor the progress of Prints in real-time
* separate administrative privileges for Managers and normal Users through an Administrator login system.
* automatic optimised allocation of prints to Machines for efficient use of the MakerSpace

To find out more about the Team behind MakerManager, please visit the <<AboutUs#, About Us>> section!

== Summary of contributions

* *Major enhancement*: Reworked GUI display of the App
https://github.com/CS2113-AY1819S1-T09-1/main/pull/83[#83]
** What it does: Displays a holistic view the current state of the MakerSpace, including highlighting the most recently modified Machines, dynamically displaying the
progress of each print, as well as dynamically updating when there are changes to Jobs or Machines.
** Justification: This feature is essential to the software, allowing MakerSpace users and managers to have a easily accessed overview of the MakerSpace that\
changes dynamically to reflect the status of Prints.

* *Major enhancement*: added the ability to edit a Machine https://github.com/CS2113-AY1819S1-T09-1/main/pull/47[#47]
** What it does: Allows a user to edit the data fields of a Machine.
** Justification: This feature is important because it allows Users to make changes to a Machine without affecting its Jobs, allowing the
app to accommodate changes in the equipment in the makerspace.

* *Major enhancement*: added commands for managing prints https://github.com/CS2113-AY1819S1-T09-1/main/pull/151[#151]
** What it does: allows users to manage prints in general, including moving, swapping, and shifting prints.
** Justification: This feature is essential to the software, allowing MakerSpace users and managers to dynamically re-arrange and re-prioritise Jobs.

* *Minor enhancement*: Non-Trivial reworking Model from storing Jobs and Machines in separate lists to storing Jobs within a List in each Machine.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/126[#126]

* *Minor enhancement*: Encapsulation of the LoggedIn state into the AdminSession object.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/82[#82]
* *Minor enhancement*: Implementation of a Timestamp object to handle time related operations.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/83[#83]
* *Minor enhancement*: Implemented automatic sorting of Jobs based on Status
https://github.com/CS2113-AY1819S1-T09-1/main/pull/151[#151]

* *Minor enhancement*: Bug reports and fixes


* *Code contributed*: https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=trufflepirate[Code Dashboard by Reposense]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.2` and `v1.4`(3 releases) on GitHub
** Enhancements to existing features:
*** Integration of undo/redo with admin commands, to prevent non-admin users from modifying actions taken by the admin.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/82[#82]
*** Integration of clear command to clear Machines and Jobs, but keep adminList for security.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/126[#126]
** Documentation:
*** Initialised Readme for MakerManager
https://github.com/CS2113-AY1819S1-T09-1/main/pull/3[#3]
*** ScreenShots and visual Aids: https://github.com/CS2113-AY1819S1-T09-1/main/pull/153[#153]

** Tools:
*** Integrated a new Github plugin (Coveralls) to the team repo to track coverage
https://github.com/CS2113-AY1819S1-T09-1/main/pull/3[#3]
*** Included Intellij CodeStyle Descriptor XML for convenient and standardised adherence to CodeStyle.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/47[#47]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===


include::../UserGuide.adoc[tag=manageJob]
include::../UserGuide.adoc[tag=findJob]
include::../UserGuide.adoc[tag=undoredo]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=managejob]


