= PLACEHOLDER - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview


== Summary of contributions

* *Major enhancement*: Reworked GUI display of the App
https://github.com/CS2113-AY1819S1-T09-1/main/pull/83[#83]
** What it does: Displays a holistic view the current state of the MakerSpace, including highlighting the most recently modified Machines, dynamically displaying the
progress of each print, as well as dynamically updating when there are changes to Jobs or Machines.
** Justification: This feature is essential to the software, allowing MakerSpace users and managers to have a easily accessed overview of the MakerSpace that\
changes dynamically to reflect the status of Prints.

* *Major enhancement*: added *the ability to edit a Machine* https://github.com/CS2113-AY1819S1-T09-1/main/pull/47[#47]
** What it does: Allows a user to edit the data fields of a Machine.
** Justification: This feature is important because it allows Users to make changes to a Machine without affecting its Jobs, allowing the
app to accommodate changes in the equipment in the makerspace.

* *Major enhancement*: added commands for managing prints https://github.com/CS2113-AY1819S1-T09-1/main/pull/151[#151]
** What it does: allows users to manage prints in general, including moving, swapping, and shifting prints.
** Justification: This feature is essential to the software, allowing MakerSpace users and managers to dynamically re-arrange and re-prioritise Jobs.

* *Minor enhancement*: Non-Trivial reworking Model from storing Jobs and Machines in separate lists to storing Jobs within a List in each Machine.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/126[#126]
* *Minor enhancement*: Integration of undo/redo with admin commands, to prevent non-admin users from modifying actions taken by the admin.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/82[#82]
* *Minor enhancement*: Encapsulation of the LoggedIn state into the AdminSession object.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/82[#82]
* *Minor enhancement*: Implementation of a Timestamp object to handle time related operations.
https://github.com/CS2113-AY1819S1-T09-1/main/pull/83[#83]
* *Minor enhancement*: Implementation of constraints on user input for various commands

* *Minor enhancement*: Bug reports and fixes


* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.2` and `v1.4`(3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
